services:
  airconnect:
    image: 1activegeek/airconnect
    container_name: airconnect
    network_mode: host
    environment:
      - AIRCAST_VAR=-x /config/config.xml
      - AIRUPNP_VAR=kill
    volumes:
      - /home/root/data/airconnect:/config
    restart: unless-stopped

  homeassistant:
    image: lscr.io/linuxserver/homeassistant:latest
    container_name: homeassistant
    network_mode: host
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Etc/UTC
    volumes:
      - /ha/config:/config
    restart: unless-stopped

  cloudflared:
    image: cloudflare/cloudflared:latest
    container_name: cloudflared
    environment:
      - TUNNEL_TOKEN=${CLOUDFLARE_TUNNEL_TOKEN}
    command: tunnel run
    restart: unless-stopped

  mosquitto:
    image: eclipse-mosquitto
    container_name: mosquitto
    network_mode: host
    volumes:
      - /ha/mosquitto/config:/mosquitto/config
      - /ha/mosquitto/data:/mosquitto/data
      - /ha/mosquitto/log:/mosquitto/log
    restart: unless-stopped

  zigbee2mqtt:
    image: koenkk/zigbee2mqtt
    container_name: zigbee2mqtt
    network_mode: host
    depends_on:
      - mosquitto
    volumes:
      - /ha/zigbee2mqtt/data:/app/data
    devices:
      - /dev/serial/by-id/usb-Itead_Sonoff_Zigbee_3.0_USB_Dongle_Plus_V2_5c36015398f3ef11966bbd1b6d9880ab-if00-port0:/dev/ttyZigbee
    environment:
      - TZ=Europe/London
    restart: unless-stopped

  node-red:
    image: nodered/node-red
    container_name: nodered
    ports:
      - "1880:1880"
    volumes:
      - ./nodered/data:/data
    restart: unless-stopped

  matter:
    image: ghcr.io/riddix/home-assistant-matter-hub:latest
    container_name: matter
    restart: unless-stopped
    network_mode: host
    volumes:
      - /ha/matter:/data
    environment:
      - HAMH_HOME_ASSISTANT_URL=http://localhost:8123
      - HAMH_HOME_ASSISTANT_ACCESS_TOKEN=${HA_MATTER_HUB_TOKEN}

  adguard:
    image: adguard/adguardhome:latest
    container_name: adguard
    restart: unless-stopped
    network_mode: host
    volumes:
      - ./adguard/work:/opt/adguardhome/work
      - ./adguard/conf:/opt/adguardhome/conf
